import './globals.css'
import NavBar from './components/navbar'
import Footer from './components/footer'

export const metadata = {
  title: 'Pelis23',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-zinc-900">
        <NavBar/>
        {children}
        <Footer/>
      </body>
    </html>
  )
}
